services:
  - type: web
    name: student-task-manager
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn taskmanager.wsgi:application
