# Generated by Django 4.2.23 on 2025-07-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
